name: Dependabot auto-merge release-updates
on: pull_request

# Based on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - id: metadata
        name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Clone self repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r '_data/release-data/requirements.txt'

      - id: latest
        name: Auto-update products
        run: python '_data/release-data/latest.py' -p 'products/' -d '_data/release-data/releases'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: products/*
          commit_message: "ðŸ¤–: Update latest release data"
          status_options: '--untracked-files=no'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

      - name: Create PR
        if: ${{ contains(steps.metadata.outputs.dependency-names, '_data/release-data') }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Comment on PR about missing releases
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            :warning: The following recent releases are not listed:
            ```
            ${{ steps.latest.outputs.warning }}
            ```
