name: Check URLs

on:
  workflow_dispatch: # Manually run workflow.
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.

jobs:
  check_urls:
    runs-on: ubuntu-latest
    # Do not run this job on forks, as it's not cool to query servers for nothing.
    if: ${{ github.repository == 'endoflife-date/endoflife.date' }}
    steps:
      - name: Checkout site
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1
        with:
          bundler-cache: true

      - name: Perform URLs check
        run: bundle exec jekyll build
        env:
          MUST_CHECK_URLS: true
